name: Deploy to Docker Hub and Swarm

on:
  push:
    branches:
      - main
      - tabnav

jobs:
  set-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set image tag using commit hash
        id: set-image-tag
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_TAG=$COMMIT_HASH
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

  build-and-push:
    runs-on: ubuntu-latest
    needs: set-image-tag
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        id: set-image-id
        run: |
          IMAGE_TAG="${{ needs.set-image-tag.outputs.image-tag }}"
          IMAGE=${{ secrets.DOCKER_USERNAME }}/meubles-by-mi:$IMAGE_TAG

  deploy-to-swarm:
    runs-on: ubuntu-latest
    needs: [set-image-tag, build-and-push]
    steps:
      - name: Set image tag variable
        run: echo "IMAGE_TAG=${{ needs.set-image-tag.outputs.image-tag }}" >> $GITHUB_ENV

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client
      - name: SSH and Pull Docker Image in Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            IMAGE=${{ secrets.DOCKER_USERNAME }}/meubles-by-mi:${{ env.IMAGE_TAG }}
            docker pull $IMAGE
            docker service update --image $IMAGE my_service_name
